name: IP Optimizer
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'
    - cron: '0 9 * * *'

jobs:
  optimize:
    runs-on: ubuntu-latest
    env:
      MODE: TCP
      PORT: 443
      RTT_RANGE: "40~250"
      LOSS_MAX: 10
      THREADS: 50
      IP_POOL_SIZE: 100000
      TEST_IP_COUNT: 200
      SPEED_URL: "https://speed.cloudflare.com/__down?bytes=10000000"
      CLOUDFLARE_IPS_URL: "www.cloudflare.com/ips-v4"
      CUSTOM_IPS_FILE: "CloudflareV4V6ip.txt"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests numpy tqdm
        sudo apt-get update
        sudo apt-get install -y net-tools

    - name: Run IP Optimizer
      working-directory: main
      run: python ip_optimizer.py

    - name: Commit results
      working-directory: main
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add results/
        git commit -m "Auto: Update optimized IPs"
        git push
