name: IP Optimizer
on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'  # UTC 21:00 = 北京时间5:00
    - cron: '0 9 * * *'   # UTC 9:00 = 北京时间17:00

jobs:
  optimize:
    runs-on: ubuntu-latest
    env:
      MODE: TCP
      PORT: 443
      RTT_RANGE: "10~2000"
      LOSS_MAX: 30
      THREADS: 50
      IP_POOL_SIZE: 100000
      TEST_IP_COUNT: 1000
      SPEED_URL: "https://speed.cloudflare.com/__down?bytes=10000000"
      CLOUDFLARE_IPS_URL: "www.cloudflare.com/ips-v4"
      CLOUDFLARE_IPS_URL_V4: "https://www.cloudflare.com/ips-v4"
      CLOUDFLARE_IPS_URL_V6: "https://www.cloudflare.com/ips-v6"
      CUSTOM_IPS_FILE: "custom_ips.txt"
      ENABLE_IPV4_POOL: 1   # 1=启用IPv4大池 0=禁用
      ENABLE_IPV6_POOL: 0   # 1=启用IPv6大池 0=禁用

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install requests numpy tqdm
        sudo apt-get update
        sudo apt-get install -y net-tools

    - name: Run IP Optimizer
      run: python ip_optimizer.py

    - name: Commit results
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add results/
        git commit -m "Auto: Update optimized IPs"
        git push
