name: IP Optimizer

on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - '**.txt'
      - '.github/workflows/ip-optimizer.yml'

jobs:
  optimize:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 查找主目录
        id: finddir
        run: |
          # 自动查找包含 ip_optimizer.py 的目录
          DIR=$(find . -type f -name "ip_optimizer.py" | head -n1 | xargs dirname)
          echo "PYDIR=$DIR" >> $GITHUB_ENV

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm numpy

      - name: 运行 IP 优选脚本
        run: python ip_optimizer.py
        working-directory: ${{ env.PYDIR }}
        env:
          CUSTOM_IPS_FILE: CloudflareV4V6ip.txt
          MODE: TCP
          PING_TARGET: https://www.google.com/generate_204
          PING_COUNT: 3
          PING_TIMEOUT: 5
          PORT: 443
          RTT_RANGE: 10~2000
          LOSS_MAX: 30
          THREADS: 50
          IP_POOL_SIZE: 10000
          TEST_IP_COUNT: 500
          TOP_IPS_LIMIT: 10
          SPEED_TIMEOUT: 5
          SPEED_URL: https://speed.cloudflare.com/__down?bytes=10000000

      - name: 上传结果到工作流产物
        uses: actions/upload-artifact@v4
        with:
          name: 优选IP结果
          path: ${{ env.PYDIR }}/results/
